var Web3 = require('web3');
//local ganache blockchain
var web3 = new Web3(Web3.givenProvider || 'HTTP://127.0.0.1:7545');

//importing the contracts artifacts generated by truffle. This also holds the abi
const MyContract = require('../build/contracts/Greeting.json')

 //create contract object
 const contract = new web3.eth.Contract(
     MyContract.abi,
     MyContract.networks['5777'].address //taken from the ganache gui - hardcoded
 );


contract.methods.getGreeting().call()
    .then((result, error) => {console.log(result, error)})

contract.methods.getGreeting().call()
    .then((result, error) => {console.log(result, error)})
