var Web3 = require('web3');
//local ganache blockchain
//var web3 = new Web3(Web3.givenProvider || 'HTTP://127.0.0.1:7545');

//importing the contracts artifacts generated by truffle. This also holds the abi
const MyContract = require('../build/contracts/TodoList.json')

 //create contract object
 /* const contract = new web3.eth.Contract(
     MyContract.abi,
     MyContract.networks['5777'].address //taken from the ganache gui - hardcoded
 ); */

 const init = async () => {
    var web3 = new Web3(Web3.givenProvider || 'HTTP://127.0.0.1:7545');
    const contract = new web3.eth.Contract(
        MyContract.abi,
        MyContract.networks['5777'].address //taken from the ganache gui - hardcoded
    );

    dueDate = await contract.methods.dueDate().call()
    console.log(dueDate)

    taskCount = await contract.methods.taskCount().call()
    console.log(taskCount)

    /* contract.methods.createTask('do laundryz').send({from: '0x2025B3b6cB02B20A75d84717725aA3Cf8b5eE2c7'})
    .on('transactionHash', function(hash){
        console.log(hash)
    })
    .on('receipt', function(receipt){
        console.log(receipt)
    })
    .on('confirmation', function(confirmationNumber, receipt){
        console.log(confirmationNumber)
    })
    .on('error', function(error, receipt) {
        console.log('error occured', error)

    }); */
 };

init();

//promise api - not a big fan yet
//contract.methods.dueDate().call()
//    .then(result => console.log(result))


