var Web3 = require('web3');
//local ganache blockchain
var web3 = new Web3(Web3.givenProvider || 'HTTP://127.0.0.1:7545');

//importing the contracts artifacts generated by truffle. This also holds the abi
const MyContract = require('../build/contracts/TodoList.json')

 //create contract object
 const contract = new web3.eth.Contract(
     MyContract.abi,
     '0xc9485cCa8Cbc04a6504029578642190328E9Ae57' //taken from the ganache gui - hardcoded
 );

console.log(contract.options.address)
//console.log(contract.taskCount)
//console.log(contract)

contract.methods.dueDate().call()
    .then(result => console.log(result))


 //console.log(MyContract.abi)
 console.log('hi')